[package]
name = "hull_white"
version = "0.1.0"
authors = ["Daniel Stahl <danstahl1138@gmail.com>"]

[dependencies]
nrfind = "1.0.2"
black_scholes = "0.2.6"
binomial_tree = "0.3.3"

[dev-dependencies]
approx = "0.2.0"